### ISSUE TITLE
Forzar a usuarios a poner fecha/hora de llegada para poder resolver ticket

### ISSUE THREAD

**Issue by salej1** [salej1/blackstar-pro#1]
Cuando se levanta un ticket, por default la fecha y hora de llegada esta en null. Esto representa el momento en que llegaron los ingenieros a resolver el problema en sitio.

En teoria las coordinadoras deben asignar la fecha y hora de llegada en los tickets una vez que los inegenieros llegan al sitio:
![image](https://user-images.githubusercontent.com/4729258/50814062-f6d90180-12dd-11e9-9f00-cd782899ab83.png)
![image](https://user-images.githubusercontent.com/4729258/50814070-02c4c380-12de-11e9-9cb4-150ccfca3efe.png)
![image](https://user-images.githubusercontent.com/4729258/50814094-1a9c4780-12de-11e9-807c-af388df35be7.png)

Una vez atendida la falla se cierra el ticket, para lo cual se requiere que haya una orden de servicio como evidencia. Hay ocasiones en los que el ticket se marca como Resuelto, que significa que el equipo ya esta funcionando pero hace falta documentacion o evidencias para cerrar el ticket.

Al dia de hoy el sistema no forza a los usuarios a tener fecha y hora de llegada para poder poner un ticket como Resuelto. Esto causa problemas porque no se puede determinar el tiempo de respuesta, asi que es necesario hacer este cambio en el sistema.

En el archivo ticketDetail.jsp se corre la funcion resolveTicket, que dispara el proceso para marcar un ticket como resuelto.
![image](https://user-images.githubusercontent.com/4729258/50814390-318f6980-12df-11e9-8315-2964ebd019b7.png)
Hay que modificar esta funcion para que antes de enviar el mensaje de confirmacion verifique que el campo Fecha y hora de llegada no este vacio.

**Comment by jvcolima** [comment]
modifico 
ticketDetail.jsp

agrego:
            <div id="resolveTicketValidation">
                <strong id = "resolveTicketValidationText"></strong>
                <form id = "resolveTicketValidationSend" action="" method="POST">
                    <input type="hidden" name="action" value = "resolveTicketValidation"/>                    
                </form>
            </div>

            if (document.getElementById("lbHoraLLegada").value.length > 8) {
                   $("#resolveTicketConfirm").dialog({ title: "Resolver Ticket " + ticketNumber });
                $("#resolveTicketConfirmText").html("Desea marcar el ticket " + ticketNumber + " como RESUELTO?");
                $("#resolveTicketConfirm").dialog("open");
                $("#resolveTicketId").val(id);
            }
            else {            
                  $("#resolveTicketValidation").dialog({ title: "Falta capturar." });
                $("#resolveTicketValidationText").html("Falta capturar el campo fecha y hora de llegada!");
                $("#resolveTicketValidation").dialog("open");
            }

            $("#resolveTicketValidation").dialog({
                autoOpen: false,
                height: 180,
                width: 330,
                modal: true,
                buttons: {
                    "OK": function() {
                    $( this ).dialog( "close" );
                }}
            });


para que si no tiene una fecha (informcion en lbHoraLLegada)
if (document.getElementById("lbHoraLLegada").value.length > 8) 
muestre el mensaje: 
**Falta capturar el campo fecha y hora de llegada!**

![image](https://user-images.githubusercontent.com/2667669/51513114-bfcf1980-1dce-11e9-8722-08950589fd15.png)
