### ISSUE TITLE
Registrar modificaciones a tickets en historial de seguimiento

### ISSUE THREAD

**Issue by salej1** [salej1/blackstar-pro#10]
Las siguientes acciones sobre tickets necesitan agregar automaticamente un registro de seguimiento en el ticket:
+ Resolver ticket
+ Cerrar ticket
+ Reabrir ticket

Los registros de seguimiento se guardan en la tabla followUp

**Comment by jvcolima** [comment]
Modifico blackstarDb_StoredProcedures.sql
los procedimientos almacenados CloseTicket, ReopenTicket y ResolveTicket para hacer uso de del procedimiento almacenado AddFollowUpToTicket para el llenado de followUp en estas acciones

![image](https://user-images.githubusercontent.com/2667669/52724500-0ef30f00-2f75-11e9-9e16-ea44909cc035.png)

![image](https://user-images.githubusercontent.com/2667669/52724507-11edff80-2f75-11e9-8508-d997e05bb931.png)

tabla followUp, realizo acciones de cerrar y reabrir para mostrar que se guarda en followUp los registros de forma correcta.
![image](https://user-images.githubusercontent.com/2667669/52724675-672a1100-2f75-11e9-8dde-262d6a0ac79d.png)

![image](https://user-images.githubusercontent.com/2667669/52724786-9e98bd80-2f75-11e9-9dfb-400221f3e245.png)

![image](https://user-images.githubusercontent.com/2667669/52724798-a22c4480-2f75-11e9-9bac-da8c44e1a2d0.png)

![image](https://user-images.githubusercontent.com/2667669/52724802-a5273500-2f75-11e9-910e-98050b67d44f.png)

![image](https://user-images.githubusercontent.com/2667669/52724807-a8babc00-2f75-11e9-9dbb-16fc56bef5f4.png)

**Comment by salej1** [comment]
@jvcolima El mensaje debe ser legible para los usuarios por favor cambialo a "Ticket Cerrado", "Ticket Resuelto" y "Ticket Reabierto"

**Comment by salej1** [comment]
@jvcolima en que branch esta este feature?

**Comment by jvcolima** [comment]
> @jvcolima en que branch esta este feature?

buenos dias si lo comente lo subi a la rama **historial-seguimiento**

**Comment by salej1** [comment]
@jvcolima 
Solo un comentario:
Esta era la forma correcta de implementarlo:
![image](https://user-images.githubusercontent.com/4729258/53324612-d9b8bc00-38a6-11e9-9865-59745d4281ac.png)
La firma del SP es AddFollowUpToTicket(pTicketId INTEGER, pCreated DATETIME, pCreatedBy VARCHAR(100), pAsignee VARCHAR(100), pMessage TEXT)

pCreatedBy es la persona que hace el comentario, pAsignee es la persona a la que se le asigna el ticket. En este caso no hay asignacion de ticket, por lo que la persona que "envia" el ticket y la que lo "recibe" es la misma

No es necesario corregir
