### ISSUE TITLE
Agregar nombre de la persona que cerro el ticket a Indicador de tickets tanto en vista web como en exportar

### ISSUE THREAD

**Issue by salej1** [salej1/blackstar-pro#11]

**Comment by salej1** [comment]
Ya que tenemos el campo closedByUsr en ticket, es necesario reportar el nombre de la persona que cerro el ticket en el Indicador de tickets, tanto en su modalidad de vista web como en su modalidad exportar.

Es necesario agregar la columna en el SP GetTicketsKPI y en el ExportHeaderConverter.

**Comment by jvcolima** [comment]
Se realiza el cambio 
en blackstarDb_Schema cambio de closedByUsr de 100 a 500
en blackstarDb_StoredProcedures cambio del SP GetTicketsKPI
en SP GetTicketsKPI se agrega IFNULL(tk.closedByUsr, '') 
en el ExportHeaderConverter se agrega .replaceAll("closedByUsr", "Cerrado por usuario"); en translateTicket
en _indServTickets agregar la columna y elmapeo el campo de closeByUsr 

![image](https://user-images.githubusercontent.com/2667669/52793621-be8eb680-3033-11e9-8c73-1d6190903a43.png)

la parte web ya esta realizada. se podría probar e integrar.

**Comment by salej1** [comment]
@jvcolima 
Tienes errores en este feature:

1. En el SP la columna no tiene alias
![image](https://user-images.githubusercontent.com/4729258/52996472-5cdb9d00-33e3-11e9-99c5-ed9f8188ef50.png)
2. Por lo tanto la columna se reporta como "IFNULL(tk.closedByUsr, '')" en el JSON:
![image](https://user-images.githubusercontent.com/4729258/52996562-9c09ee00-33e3-11e9-99aa-0fea4d05ef9e.png)
3. Esto causa que el indicador no funcione:
![image](https://user-images.githubusercontent.com/4729258/52996642-d4a9c780-33e3-11e9-9dfd-b8315abfff0d.png)

Esto quiere decir que no probaste el feature. No puedes subir codigo que no has probado!

No es necesario que lo arregles, ya esta arreglado, solo haz pull de master.

**Comment by jvcolima** [comment]
> Esto quiere decir que no probaste el feature. No puedes subir codigo que no has probado!
> 
> No es necesario que lo arregles, ya esta arreglado, solo haz pull de master.






******
Esto quiere decir que no probaste el feature. No puedes subir código que no has probado!
Esta parte la probé pero llene con info el campo, posterior a eso vi que tenias una validación para nulos, la agregue y allí fue donde ya no probé, di por echo que funcionaria, pero tienes razón con el alias de que se me paso probar con el alias.
