### ISSUE TITLE
Verificar equipos del CM2515, aparecen con CS Altamira pero no estan asignados al CS

### ISSUE THREAD

**Issue by salej1** [salej1/blackstar-pro#12]
Verificar por que en el ticket [18-51](http://gposac-blackstar-pro.appspot.com/ticketDetail?ticketId=1529) se asocia el equipo con el centro de servicio Altamira cuando en la [poliza](http://gposac-blackstar-pro.appspot.com/policies/policyDetail.do?projectNumber=CM2515) el equipo no esta asociado al centro de servicio.

Checar si hay mas casos

**Comment by salej1** [comment]
En el ticket
![image](https://user-images.githubusercontent.com/4729258/53328720-38cefe80-38b0-11e9-9dd1-16c431d3f14e.png)

En la poliza
![image](https://user-images.githubusercontent.com/4729258/53328779-5308dc80-38b0-11e9-89f7-99a9cd05b905.png)

**Comment by jvcolima** [comment]
Lo extraño es que en la poliza si tiene centro de servicio altamirano, lo revise a nivel de la tabla. 

![image](https://user-images.githubusercontent.com/2667669/53744986-c9cf4800-3e63-11e9-9ecb-002c39d23cb7.png)
