### ISSUE TITLE
Permitir capturar reportes de mantt preventivo (AA, UPS, BB, PE) a sub-equipos de estaciones de microondas

### ISSUE THREAD

**Issue by salej1** [salej1/blackstar-pro#13]
Al momento de capturar una orden de servicio preventivo se teiene que seleccionar el tipo de equipo que se va a atender. Los tipos disponibles son:
Aire Acondicionado (AA)
Banco de Baterias (BB)
Planta de Emergencia (PE)
UPS

Estos reportes solo los pueden capturar los ingenieros de servicio

Al generar un reporte de estos, el sistema pide al usuario que capture el numero de serie del equipo a atender y muestra un auto-completable con la lista de quipos que coinciden con la parte del numero de serie capturado. El sistema no permite capturar una orden de servicio para un equipo que no este en la lista.

El problema surge con las estaciones de microondas, ya que sus equipos no estan capturados de forma individual, por lo que es necesario que aparezcan en la lista de todos los tipos de reporte para poder ser atendidos de forma preventiva.

Lo que se requiere es que el listado de equipos que aparece al intenar capturar una orden de cualquiera de los tipos mencionados se incluyan los equipos tipo estacion de microondas.

**Comment by jvcolima** [comment]
Los grupos de usuario que serian son:
Implementacion y Servicio
e
Ingeniero de Centro de Servicio

**Comment by jvcolima** [comment]
![image](https://user-images.githubusercontent.com/2667669/53672036-80ee7800-3c46-11e9-9c6f-ffa5a0fa11b8.png)

![image](https://user-images.githubusercontent.com/2667669/53672044-8cda3a00-3c46-11e9-8d99-c205d5c9d6f6.png)

![image](https://user-images.githubusercontent.com/2667669/53672074-9c598300-3c46-11e9-8ed8-611e177521b3.png)

las llamdas estan harcodeadas y no cambia por  'K'
showEquipmentSelect('X')
showEquipmentSelect('A')
showEquipmentSelect('B')
showEquipmentSelect('P')
showEquipmentSelect('U')

el cambio en el PA GetEquipmentByType

![image](https://user-images.githubusercontent.com/2667669/53672126-c612aa00-3c46-11e9-9a05-e074ac63b833.png)

**Comment by salej1** [comment]
@jvcolima 
A pesar de que el cambio aparentemente funciona, no esta bien implementado. El objetivo era incluir las estaciones de microondas en el listado y efectivamente se incluyen, pero tambien se inclyuen todos los demas equipos, ahora aparecen todos los equipos al seleccionar cualquier tipo de reporte. 

Por el momento lo deployee asi para que los usuarios tengan la funcionalidad pero hay que corregirlo e implementarlo bien.

**Comment by jvcolima** [comment]
Se hace la modificacion en el PA GetEquipmentByType 
![image](https://user-images.githubusercontent.com/2667669/53763151-986c7180-3e8f-11e9-97cf-f6ef27bb0293.png)

para que no muestre todos los equipos en todas las consultas sino que muestre
- aires acondicionados y estaciones de microondas
- baterias y estaciones de microondas
- ups  y estaciones de microondas
- plantas de emergencia y estaciones de microondas

se probo y se sube de nuevo a git a la rama 
**mantt-preventivo-AA-UPS-BB-PE**
