### ISSUE TITLE
Indicador de fallas recurrentes regresa Error

### ISSUE THREAD

**Issue by salej1** [salej1/blackstar-pro#2]
El indicador de fallas recurrentes regresa el siguiente error al intentar consultarlo:
![image](https://user-images.githubusercontent.com/4729258/49853011-6de8ac00-fdab-11e8-8b54-ef8db955d9ba.png)

**Comment by jvcolima** [comment]
creo que no tengo permisos. no se si me puedas asignar y poder asi mover el card

**Comment by salej1** [comment]
Jorge, recuerda que tienes que ir poniendo en el ticket tu razonamiento del problema, tu hipotesis y tu propuesta de solucion. 

Friendly reminder

**Comment by jvcolima** [comment]
@salej1 se tienen algún documento con nomenclaturas de como declarar tablas, campos, nombres en declaración de variables, etc. solo visualizo que debe ser en ingles. pero no se si exista algún documento que pueda leer y me sirva como base.

**Comment by DeliriumTremens** [comment]
Que tal Sergio, ojalá estes muy bien. Veo que se reactivo el proyecto,
seguro llegara a buen puerto. Ayudame por favor a desuscribirme de las
notificaciones.

Saludos.

**Comment by salej1** [comment]
@jvcolima No tenemos un documento para el standard de nomenclatura pero basicamente son estas reglas:
1. Los nombres se ponen en ingles procurando poner un nombre significativo
2. Las tablas se nombran usando camelCase en singular
3. Los campos se nombran usando camelCase en singular
4. Los ids deben incluir el nombre de la tabla. Ej: ticketId

**Comment by salej1** [comment]
@jvcolima 
Acerca de tu propuesta de solucion:
1. Que campos propones meter en la tabla?
2. Que cardinalidad tendra con polizas y tickets?
3. Cambia el nombre de la tabla a ticketSummary, ya que realmente estamos de-normalizando tickets y polizas
4. Agrega una descripcion mas detallada de tu propuesta

Gracias!

**Comment by salej1** [comment]
Se sugiere poner y nombrar los campos de tiketSumary asi:

ticketSummaryId
lastTicketId
previousTicketId
lastService
lastServiceDate
lastServiceEmployee
