### ISSUE TITLE
Error al crear ticket provoca multiplicacion de tickets

### ISSUE THREAD

**Issue by salej1** [salej1/blackstar-pro#6]

**Comment by salej1** [comment]
Los usuarios reportan que al crear un ticket el sistema regresa un mensaje de error
![image](https://user-images.githubusercontent.com/4729258/51856161-9f362080-22f4-11e9-86c3-9e806e0cca66.png)
Al parecer si se esta guardando el ticket porque cuando lo reintentan el ticket se duplica la cantidad de veces que se reintento.

Al buscar en el log de errores, este es el error que aparece:
![image](https://user-images.githubusercontent.com/4729258/51856221-c7be1a80-22f4-11e9-9e3d-a2a6040ba3db.png)

Esto quiere decir que en las operaciones post-guardado del ticket estamos corriendo un query que deberia regresar solo 1 row pero esta regresando mas.

@jvcolima es urgente corregir este problema por favor dale prioridad a este issue.

**Comment by jvcolima** [comment]
subi a la ram bug2 la correcion. 

omitiendo
![image](https://user-images.githubusercontent.com/2667669/51867267-b71b9d80-2310-11e9-9270-7ad18f4d17b8.png)

dejando solo insert en ticketSummary
![image](https://user-images.githubusercontent.com/2667669/51867294-c8fd4080-2310-11e9-99af-ccdae03dfbae.png)

**Comment by jvcolima** [comment]
- para mitigar el error comentamos limpiar ticketSummary 
- subi a git el cambio donde inserta siempre, el ultimo y anterior ticket
