### ISSUE TITLE
Generar reporte de tickets por zona

### ISSUE THREAD

**Issue by salej1** [salej1/blackstar-pro#7]
Se requiere generar reporte de tickets por zona segun el usuario que esta logeado en el portal.

PEMEX nos provee los siguientes datos:

FRANCISCO AQUINO ICHANTE | ZM
JESÚS RICARDEZ DE LOS SANTOS | ZS
CESAR ROBERTO CANCINO PEÑA | ZGS
PEDRO ORTÍZ ROJAS | ZGN
RAFAEL GUTIÉRREZ MORALES | ZCN

Necesitamos agregar mapear las zonas a los usuarios, para esto hay que hacer lo siguiente:

Parte 1
1. Agregar una tabla nueva userZone con los campos:
* userZoneId (INT AUTOINCREMENT)
* zone
2. Agregar una columna 'userZoneId' a la tabla blackstarUser
3. Agregar en el script blackstarDb_data el llenado de datos de la tabla userZone y la columna userZoneId a los usuarios mencionados arriba
* Tener cuidado de que solo se llene si esta vacio el campo
4. Modificar los SP GetTicketsKPI para el indicador de tickets del siguiente modo:
* Agregar un parametro zone
* Si el parametro zone NO ES NULL, reportar todos los tickets cuya poliza este asociada a el usuario correspondiente a la zona. La relacion es la siguiente:
* pZone (parametro) nos permite encontrar el email del usuario correspondiente a la zona en blackstarUser --> Una vez teniendo el usuario tenemos su correo y buscamos sus polizas asociadas en policyEquipmentUser --> Una vez teniendo sus polizas jalamos los tickets asociados a esas polizas usando ticket.policyId
5. Modificar los parametros de las funciones (tanto en interfaces como en implementaciones) por las que pasa este flujo desde el controller hasta el dao agregando el nuevo parametro de filtro 'zone'
6. Agregar un dropdown list en el indicador de tickets que permita a los usuarios filtrar por zona, similar a al filtro que hay por equipo en el indicador de Disponibilidad (Graficas Generales)
![image](https://user-images.githubusercontent.com/4729258/52149888-e5acb780-2633-11e9-987f-e61a1bf64b7c.png)
7. Por ultimo enviar el parametro nuevo desde el front en el request que va al backend para que sea utilizado en el SP de GetTicketsKPI

Parte 2
Implementar el mismo filtro para el indicador de Exportacion de tickets, en este caso el parametro de zonas puede requerirse en una ventana de pop up

**Comment by jvcolima** [comment]
leí y creo que no tendré problema, lo veo como algo que debo poder sacar, solo que si es algo de "talacha" por así decirlo, no le veo tanto reto tecnifico, sino mas bien de comprensión del proceso y "talacha"

**Comment by salej1** [comment]
@jvcolima cual es el status de este feature y por que no lo has subido a un branch?

**Comment by salej1** [comment]
@jvcolima por favor recuerda poner en que branch esta el feature cuando lo pases a deploy-ready

**Comment by jvcolima** [comment]
la rama se llama tickets-zona

**Comment by salej1** [comment]
@jvcolima 
No sacaste tu branch de una copia fresca de master, es de una copia anterior:
![image](https://user-images.githubusercontent.com/4729258/53857822-50d40b80-3f9d-11e9-9833-2f7727b18000.png)

Tampoco estan los cambios a BD, solo los cambios a codigo:
![image](https://user-images.githubusercontent.com/4729258/53857849-6ba68000-3f9d-11e9-8611-848f3be63c2b.png)

**Comment by jvcolima** [comment]
Buenos días Sergio, esa rama no la he subido, ayer estuve depurando tenia muchas ramas demás de los features y bugs anteriores y de tickets-zona teina 3 ramas y estuve revisando cual era la correcta, y posterior a eso probando tickets-zona-java8
subiré la rama el feature a la rama **tickets-zona-java8** dia de hoy

![image](https://user-images.githubusercontent.com/2667669/53889934-e3e86200-3fec-11e9-8138-078014dcda49.png)

**Comment by salej1** [comment]
@jvcolima 
Creo que no le diste push a tu branch tickets-zona-java8
![image](https://user-images.githubusercontent.com/4729258/53931569-4c6e2800-405b-11e9-81d1-cac532da1621.png)

**Comment by jvcolima** [comment]
Subí el Feature a la rama **tickets-zona-j8**

**Comment by salej1** [comment]
@jvcolima 
Observaciones de tu patch:

1. Por que el statement que agrega la columna zoneId esta dentro de este IF? Debe tener su propio if
![image](https://user-images.githubusercontent.com/4729258/54010096-0ab0b080-4133-11e9-91b0-27c8a144f861.png)

2. pZone deberia ser INT, se supone que recibe el ZoneId seleccionado por el usuario
![image](https://user-images.githubusercontent.com/4729258/54010234-91fe2400-4133-11e9-816b-3669377b332e.png)

3. En el SP GetTicketsKPI duplicaste todo el SP para agregar un filtro. La forma correcta de hacerlo es como se hace con los demas filtros --> Si es null el filtro es 1 = 1 si no se aplica el filtro
![image](https://user-images.githubusercontent.com/4729258/54010488-9119c200-4134-11e9-8cda-81d93d607faa.png)

4. Las zonas son ZM, ZS, ZGS, ZGN, y ZCN, los nombres son el usuario al que pertenece la zona, pero el nombre del usuario NO es parte del nombre de la zona
![image](https://user-images.githubusercontent.com/4729258/54010667-519fa580-4135-11e9-9a4b-48fc5b7e5886.png)

5. El campo debe ser un dropdown list como lo pide el requerimiento y su valor debe ser un entero, que es el userZoneId.

6. En todo el stack de llamadas, el parametro pZone debe ser entero y el valor que debe llevar es el userZoneId

7. El script de cambios a la BD no corre
![image](https://user-images.githubusercontent.com/4729258/54011224-61b88480-4137-11e9-9c6e-a98501ec9c32.png)

Le falta el ; al final del Update
![image](https://user-images.githubusercontent.com/4729258/54013010-62ecb000-413d-11e9-9c8f-7d95e97cad61.png)

8. ticketSummeryId no tiene nada que hacer aqui
![image](https://user-images.githubusercontent.com/4729258/54013120-ae06c300-413d-11e9-9fa1-fb7087e82607.png)

9. Correr el indicador de tickets sin parametros no regresa tickets
![image](https://user-images.githubusercontent.com/4729258/54013462-d216d400-413e-11e9-9423-440f0b9921d0.png)

**Comment by jvcolima** [comment]
Las correcciones que me comentas ya las realice pero 
me esta costando creo que es jquery  o como unir el campo desde el front hacia el back y haga el filtrado 

revise varios auto complete, pero no ubico bien los parametros a indicar.
init_autoComplete(data, "txt_ticketISRPR", "dummy_txt_ticketISRPR", "single")

init_autoComplete(policies, 'serialNumber', 'policyId', "single", function(refId){
        policyId = $('#policyId').val();

        go('getCharts', null, '&policyId=' + policyId);
      });

EN MI LOCAL
![image](https://user-images.githubusercontent.com/2667669/54033578-4ae75180-417a-11e9-8b15-d05e20fea978.png)

EN LINEA
![image](https://user-images.githubusercontent.com/2667669/54033687-97329180-417a-11e9-975f-5123e79f1033.png)

**Comment by jvcolima** [comment]
El unico punto que tuve duda es el 4, porque comentas 
los nombres son el usuario al que pertenece la zona, pero el nombre del usuario NO es parte del nombre de la zona

entonces debe ir una columna mas con el nombre del usuario?
o en que momento hace match para actualizar en blackstarUser su userZoneId
porque ahorita hago match con el nombre del usuario pero deberia agregar un campo mas en userZone con el nombre del usuario o sigo confundido con esto como hacer el match inicial. posterior si ubico que sera con el userZoneId

![image](https://user-images.githubusercontent.com/2667669/54034581-d9f56900-417c-11e9-9f55-e0b52532f376.png)

**Comment by jvcolima** [comment]
me sigue pasando el error y limite en la consulta a pocos registros y no hay problema. 

![image](https://user-images.githubusercontent.com/2667669/54040991-3ad86d80-418c-11e9-8dd7-f5faf3f7fcd2.png)

Lo que acabo de corregir es: 
- Corregi el punto 4, solo inserte la zona ZM, ZS, ZGS, ZGN, ZCN
**y mi duda es en este punto hago un update del userZoneId ? ya que segun el orden que se inserten
seria ZM=1, ZS=2, ZGS=3, ZGN=4, ZCN=5
entonces si identifico su id para asociar a su respectiva persona en estas primeras inserciones
y posterior a eso ya que se haga la relacion de forma manual.**

Lo que estoy haciendo es:
**- Ver porque el JSON "truena" en el parseo (dedicare 2 hrs maximo)
- Revisare algunos ejemplos que ya se tienen (flujo) de comunicacion del front con la parte del back
- Vere mas sobre llamadas asíncronas con ajax en java.**

el fature #7 de tickets por zona y #15 reporte con filtros... 
son muy similares el 15 es mas sencillo y te aviso en 2 hrs como voy  y en que me atoro.

**Comment by salej1** [comment]
@jvcolima 
contestando a tu pregunta:
Puedes poner el id autonumerico y hacer la inservion solo de los valores. La asignacion a mano, son 5 registros no es mucho problema

**Comment by jvcolima** [comment]
> @jvcolima
> contestando a tu pregunta:
> Puedes poner el id autonumerico y hacer la inservion solo de los valores. La asignacion a mano, son 5 registros no es mucho problema

si asi coloque autonumerico. como comentas son pocos registros y no debe haber problema.
- ya estan las correciones del 1 al 8. me falta la nueve
- no he podido detectar la causa del error de json
- y estoy viendo la parte de llamadas asincronas con ajax

**Comment by jvcolima** [comment]
Se sube a la rama **tickets-zona-j8**
Se insertan las zonas solo si no existe información, pero no se realiza la asociación, esto se realizara a mano.

Se realizan cambios que me comentaste:

ok - Tienes que crear una clase POJO nueva que se llame UserZone que represente la tabla

Tienes que crear estos metodos nuevos:
ok - ServiceIndicatorsService.getUserZones
ok - ServiceIndicatorsServiceImpl.getUserZones
ok - ServiceIndicatorsDao.getUserZones
ok - ServiceIndicatorsDaoImpl.getUserZones
		ok - Todos los metodos regresan una lista de objetos UserZone
ok -  Tienes que crear este SP getUserZones


ok
Desde el controller ServiceIndicatorsController, en el metodo de getTickets haces 
la llamada a getUserZones en el service para traerte la lista de zonas y 
metes el resultado en un model attribute. Ese model attribute lo lees desde el JSP

**Comment by salej1** [comment]
@jvcolima 
Tu patch todavia tiene errores

1. No agregaste el SP GetUserZones al script blackstarDb_StoredProcedures.sql
![image](https://user-images.githubusercontent.com/4729258/54414273-334e2280-46be-11e9-8637-b0fb75ac2fd3.png)

2. El parametro en las funciones lo agregaste como String, debe ser Integer
![image](https://user-images.githubusercontent.com/4729258/54415254-5af2ba00-46c1-11e9-9ebc-e770928b2ebc.png)

3. Una vez seleccionada una zona, al regresar a Todas el reporte falla con este error:
![image](https://user-images.githubusercontent.com/4729258/54416695-bf177d00-46c5-11e9-85a9-2ec8fdc8f463.png)
Lo puedes arreglar con este filtro 
![image](https://user-images.githubusercontent.com/4729258/54417551-20405000-46c8-11e9-8586-566a03613cca.png)

4. No implementaste el filtro de zona para la exportacion de tickets y ahora truena con este error:
![image](https://user-images.githubusercontent.com/4729258/54417520-07379f00-46c8-11e9-955f-625b606eadcf.png)

**Comment by salej1** [comment]
@jvcolima 
Por que no has entregado este feature? Cual es el estatus?

**Comment by jvcolima** [comment]
buenos días Sergio hice las correcciones en el feature #15 porque también tiene 2 filtros.
y me había atorado con 

1.- correccion cuando regresaba a Tod@s en los filtros
me ayudaste con esto
![image](https://user-images.githubusercontent.com/2667669/54692148-22e8de00-4aea-11e9-88bf-955091d00930.png)

2.- me faltaban las pruebas finales pero ya pase de feature #15 al #7 lo subo en un momento y te confirmo

**Comment by jvcolima** [comment]
> 4\. No implementaste el filtro de zona para la exportacion de tickets y ahora truena con este error:

De estos los 3 primeros puntos estan en la rama **tickets-zona-j8** probados
el punto 4, es el que estoy probando para subir, porque ese agregue el pop up ayer antes de que exporte pida la zona, pero probando para no subirlo mal

**Comment by jvcolima** [comment]
subo evidencia de filtrazo por zona en tickets
![image](https://user-images.githubusercontent.com/2667669/54734818-fc698800-4b67-11e9-967a-e62533408288.png)

subo evidencia de filtrazo por zona en exportacion de tickets, filtrando por una zona o incluso por todas.
![image](https://user-images.githubusercontent.com/2667669/54734852-3fc3f680-4b68-11e9-98f4-7604ec0bd996.png)

![image](https://user-images.githubusercontent.com/2667669/54734854-45214100-4b68-11e9-8761-ac060c32f213.png)
![image](https://user-images.githubusercontent.com/2667669/54734865-52d6c680-4b68-11e9-9bf0-3e315cb5a26e.png)

**Comment by salej1** [comment]
@jvcolima 
Ok, ya esta todo el codigo en el branch tickets-zona-j8?

**Comment by jvcolima** [comment]
> @jvcolima
> Ok, ya esta todo el codigo en el branch tickets-zona-j8?

si subi todo el codigo, y evidencia espero que ya no te de nada de problemas, subire el feature #15 en un rato ando probando, quiero probar y que sirva lo que subo.

**Comment by salej1** [comment]
Ok, hago pruebas y si todo sale bien hago el deploy

**Comment by salej1** [comment]
Algunas observaciones:
1. El select que pusiste en indicadoresServicios.jsp le dejaste el bind al evento onchange, de modo que cuando se selecciona una zona desde el flujo de Exportar Tickets se manda un request que no es necesario
![image](https://user-images.githubusercontent.com/4729258/54736302-16a76400-4b70-11e9-9510-89c73184c2f6.png)

2. Dejaste el mismo id en el select para el indicador normal y para el export, esto hace que se interfieran entre si cuando los 2 estan visibles y el valor del select del pop up queda ignorado
![image](https://user-images.githubusercontent.com/4729258/54736852-ba920f00-4b72-11e9-9017-9f1cacba0097.png)
![image](https://user-images.githubusercontent.com/4729258/54736882-e01f1880-4b72-11e9-9b12-612d97c8fa20.png)

3. Te falto agregar la llave foranea de blackstarUser.userZoneId a userZone.userZoneId
![image](https://user-images.githubusercontent.com/4729258/54737764-08a91180-4b77-11e9-9c5b-14be403b555b.png)

4. El tipo de userZoneId estaba mal en el POJO UserZone
![image](https://user-images.githubusercontent.com/4729258/54741910-7825fd80-4b85-11e9-8f5d-ba0ef4e35d7f.png)

Ya hice yo las correcciones, solo haz pull de master e integra en el branch del issue 15
