### ISSUE TITLE
Registrar Nombre de la persona que cierra el ticket

### ISSUE THREAD

**Issue by salej1** [salej1/blackstar-pro#8]
El ultimo requerimiento que falta por implementar de la lista de cambios solicitada por ESI Consultores es registrar el usuario que cierra el ticket.

Para esto tenemos que agregar un campo 'closedByUsr' a la tabla ticket y asignarlo en el SP CloseTicket
Considerar que sera necesario agregar este parametro desde doPost en blackstarWeb/src/com/blackstar/web/TicketDetail.java

**Comment by jvcolima** [comment]
blackstarDb_CreateSchema - agregando el campo closedByUsr
blackstarDb_StoredProcedures - y en el procedimiento almacenado CloseTicket se agrega t.closedByUsr = pModifiedBy,

no se modifica en TicketDetail porque en doPost ya envia un parametro, donde envia el correo.
la ultima persona que modifica, en este caso es la misma que modifica y cierra en la accion closeTicket

![image](https://user-images.githubusercontent.com/2667669/52526833-9e9e7200-2c84-11e9-880c-38c2df49cc27.png)

![image](https://user-images.githubusercontent.com/2667669/52526828-934b4680-2c84-11e9-8e0a-7953aa8166ba.png)


![image](https://user-images.githubusercontent.com/2667669/52526830-99412780-2c84-11e9-95a6-53f74dba9454.png)

**Comment by salej1** [comment]
@jvcolima un par de comentarios con este cambio:
1. Se te siguen yendo espacios en blanco, por favor configura tu editor para que los elimine automaticamente.
2. Usa campos mas grandes, sobrados de espacio cuando uses texto (minimo 500)
![image](https://user-images.githubusercontent.com/4729258/52612424-3d76ca00-2e4f-11e9-8621-f65dab230799.png)
