### ISSUE TITLE
Asignar automaticamente organizacion a usuarios con perfil de call center externo

### ISSUE THREAD

**Issue by salej1** [salej1/blackstar-pro#9]
Hay un perfil de usuario 'Call Center Externo' cuyos usuarios deben tener organizationId = 2 en la tabla blackstarUser
![image](https://user-images.githubusercontent.com/4729258/52494439-9e727980-2b93-11e9-95bd-43c3ee79f4b8.png)

Es necesario modificar el SP CreateUserGroup para detectar cuando se inserta un usuario con este perfil y en dicho caso asignar organizationId = 2 para el usuario

**Comment by jvcolima** [comment]
En teoría el cambio es sencillo en el PA CreateUserGroup si el pGroupName = 'Call Center Externo', actualizamos el campo organizationId = 2 en la tabla blackstarUser

![image](https://user-images.githubusercontent.com/2667669/52677286-f04c3400-2ef2-11e9-9288-d1f20e45c73a.png)

![image](https://user-images.githubusercontent.com/2667669/52677308-01954080-2ef3-11e9-9214-bf83ae3fd6bf.png)


![image](https://user-images.githubusercontent.com/2667669/52677294-f3dfbb00-2ef2-11e9-9d62-df4642654708.png)


![image](https://user-images.githubusercontent.com/2667669/52677298-f6daab80-2ef2-11e9-9384-07244767dc82.png)


![image](https://user-images.githubusercontent.com/2667669/52677302-f9d59c00-2ef2-11e9-9ebe-ab8cce10740d.png)

**Comment by salej1** [comment]
@jvcolima por que eliminaste el ServiceIndicatorsController y ServiceIndicatorsServiceImpl en este branch?
![image](https://user-images.githubusercontent.com/4729258/52688969-2a7efb00-2f1e-11e9-8791-6dc9a7cdafea.png)

**Comment by salej1** [comment]
Otra vez espacios en blanco
![image](https://user-images.githubusercontent.com/4729258/52689108-a6794300-2f1e-11e9-8657-adc1c283879c.png)

**Comment by salej1** [comment]
Hay un typo en el patch, debe ser blackstarUser, no blackstaruser, esto truena en produccion
![image](https://user-images.githubusercontent.com/4729258/52689583-4a172300-2f20-11e9-9293-dbb12f0bb895.png)

**Comment by jvcolima** [comment]
> @jvcolima por que eliminaste el ServiceIndicatorsController y ServiceIndicatorsServiceImpl en este branch?
> ![image](https://user-images.githubusercontent.com/4729258/52688969-2a7efb00-2f1e-11e9-8791-6dc9a7cdafea.png)
 
fue un error de dedo por los cambios de branch, espero no vuelva a suceder.

**Comment by jvcolima** [comment]
> Otra vez espacios en blanco
> ![image](https://user-images.githubusercontent.com/4729258/52689108-a6794300-2f1e-11e9-8657-adc1c283879c.png)

ando revisando ya antes de subir con git diff
y ya revise en notepad ++ y sublimetext. mismo caso espero ya no se repita y tener mas atención

**Comment by jvcolima** [comment]
> > Otra vez espacios en blanco
> > ![image](https://user-images.githubusercontent.com/4729258/52689108-a6794300-2f1e-11e9-8657-adc1c283879c.png)
> 
> ando revisando ya antes de subir con git diff
> y ya revise en notepad ++ y sublimetext. mismo caso espero ya no se repita y tener mas atención

cambios de textos realizados y subidos a git.
